// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /* tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], */

  // But you can create a sidebar manually
  
  DocsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['tutorial-basics/housekeeping',
              'tutorial-basics/get-omni',
              'tutorial-basics/create-accounts',
              'tutorial-basics/deploy',
              
      ],
             
    },

    {
      type: 'category',
      label: 'Learn',
      items: ['learn/why-omni',
              'learn/architecture',
              'learn/accounts',
              'learn/transactions',
              'learn/consensus',
              'learn/tokenomics',

              
      ],
             
    },

    {
      type: 'category',
      label: 'Tooling',
      items: ['tooling/blockexp',
              'tooling/bridges',
              'tooling/faucets',
            

              
      ],
             
    },

    {
      type: 'category',
      label: 'Nodes',
      items: ['nodes/introduction',
              'nodes/components',
              'nodes/run-node',
            

              
      ],
             
    },
  ],
   
};

export default sidebars;
